<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\DocuMind.Core\DocuMind.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.20" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.20">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.5-beta1" />
		<PackageReference Include="PdfPig" Version="0.1.14-alpha-20251224-7c4f5" />
		<PackageReference Include="RestSharp" Version="113.0.1-alpha.0.3" />
		<PackageReference Include="Serilog" Version="4.3.1-dev-02395" />
		<PackageReference Include="Serilog.Sinks.File" Version="8.0.0-dev-02318" />
		<PackageReference Include="System.Drawing.Common" Version="10.0.1" />
		<PackageReference Include="Tesseract" Version="5.2.0" />
		<PackageReference Include="UglyToad.PdfPig" Version="1.7.0-custom-5" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Logging\" />
	</ItemGroup>

</Project>