<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
	  <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="6.2.1" />
    <PackageReference Include="Markdig.Wpf" Version="0.5.0.1" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Serilog" Version="4.3.1-dev-02395" />
    <PackageReference Include="Serilog.Sinks.File" Version="8.0.0-dev-02318" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Styles\" />
    <Folder Include="tessdata\" />
    <Folder Include="Utilities\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocuMind.Core\DocuMind.Core.csproj" />
    <ProjectReference Include="..\DocuMind.Infrastructure\DocuMind.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="tessdata\eng.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="tessdata\tur.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
